filebeat.inputs:
  - type: log
    paths:
      - /var/logs/yetki-yonetimi-api/*.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"


setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"


setup.kibana:
  host: "http://kibana:5601"
