receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp:
    endpoint: "http://jaeger:4317"  # Jaeger'a OTLP gRPC üzerinden veri gönderimi

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]